### PR TITLE
Update dependencies to contao 4.13

### PR DESCRIPTION
**Pull request by rabauss**
After merging #64 + #66 a new minor Release should be published.
Afterwards this PR should be rebased - which reverts als changes from the compatiblity PRs
Then the dependencies are updated to contao 4.13 and a new release could be created!

### CODE REVIEW

**Comment by Toflar** [comment]
We could tag main now - any reason why it needs to be a minor update?

**Comment by rabauss** [comment]
I was not sure how "big" the update will be - just tag a release which is compatible for the legacy 4.9 again ;-)
We could also wait a little bit until merging this PR :-D

**Comment by Toflar** [comment]
Done :)

**Comment by rabauss** [comment]
I think this PR could be merged to be only compatible with 4.13 again!

**Comment by Toflar** [comment]
Done

**Pull request merged**
