### PR TITLE
Displaybugs contao4

### PR DESCRIPTION
**Pull request by NicolasGoerlach**
fixed some displaybugs for/in contao4

### CODE REVIEW

**Comment by aschempp** [comment]
Will this still be compatible with Contao 3.5?

**Comment by NicolasGoerlach** [comment]
Currently not, sorry, we got no svg on Contao 3.5 so we need to change it only on Contao 4. (f010732)
I dont know why we need to declare a specific icon for imageSizes if it works automatically for the other shortcuts. Maybe you can have a look at it? The other changes still work in Contao 3.5

**Comment by NicolasGoerlach** [comment]
k, got it – works now fine in 3.5 and 4

**Comment by aschempp** [comment]
I think we can ignore the backend icon, as they are obsolete since Contao 4.2 (the new backend theme). I have added the necessary CSS for group icons in Contao 4.4 in adacf974ad3a5516ea8908f8cab08211197bce6f and fixed the checkbox view in 95bde8e13f93709dca8e4bbc9e6259c39efe112e.

@Toflar still need to check the other CSS fixes as the javascript options seem not to work in Contao 4.4 anymore

**Comment by Toflar** [comment]
Should be all fixed in the meantime!

**Pull request closed without merging**
